unbind C-b
set -g prefix C-space

set -g default-terminal "screen-256color"
set -g status-position bottom
set -g status-bg color234
set -g status-fg color137
set -g status-left ''
set -g status-right '#[fg=color233,bg=color241,bold] %d/%m #[fg=color233,bg=color245,bold]%H:%M:%S'
set -g status-right-length 50
set -g status-left-length 20

setw -g window-status-current-format ' #I#[fg=color250]:#[fg=color255]#W#[fg=color50]#F '
setw -g window-status-format ' #I#[fg=color237]:#[fg=color250]#W#[fg=color244]#F '

#source-file
bind r source ~/.tmux.conf \; display "tmux Config sourced!"
bind enter split-window -h
bind shift-enter split-window 
bind Q killw
bind L list-sessions
bind d detach
bind a attach
bind l nextl
bind k next
bind j prev
bind r resizew
